# Generated by Django 3.2.7 on 2021-09-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='packageImage/blank.png', null=True, upload_to='product-image')),
                ('name', models.CharField(max_length=40)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='miswarfashionApp.category')),
            ],
        ),
    ]
