# Generated by Django 3.2.7 on 2021-09-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miswarfashionApp', '0002_auto_20210925_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='packageImage/blank.png', null=True, upload_to='product-image')),
            ],
        ),
    ]
